#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\empmod.bof
BOFS = pierceemp.bof \
       thrustemp.bof \
       slashemp.bof \
       bludgeonemp.bof \
       magicemp.bof \
       weaponemp.bof \
       holyemp.bof \
       unholyemp.bof \
       acidemp.bof \
       shockemp.bof \
       coldemp.bof \
       fireemp.bof \
       punchemp.bof

!include $(KODDIR)\kod.mak
