#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\witchery.bof
BOFS = arcaneknowledge.bof \
       rotememorization.bof \
       efficientcasting.bof \
       ancientpact.bof \
       unhallowedrunes.bof \
       bloodrunes.bof \
       ostracization.bof \
       hermitage.bof \
       nightgrip.bof \
       aversion.bof \
       manashield.bof \
       viletouch.bof

!include $(KODDIR)\kod.mak
