#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\knightcraft.bof
BOFS = heavyarmor.bof mediumarmor.bof fortitude.bof zealousfervor.bof \
       bravery.bof

!include $(KODDIR)\kod.mak
