#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\majorhstone.bof
BOFS = majorhstonred.bof majorhstonblu.bof majorhstonsky.bof majorhstonbrn.bof \
       majorhstongre.bof majorhstonblk.bof majorhstonwht.bof majorhstondkgre.bof \
       majorhstonpurp.bof

!include $(KODDIR)\kod.mak
