#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\charmspel.bof
BOFS = charminsect.bof \
       charmanimal.bof \
       charmundead.bof \
       charmhumanoid.bof

!include $(KODDIR)\kod.mak
