#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\atakspel.bof
BOFS = boltspel.bof \
       earthqua.bof radproj.bof \
       monsterquake.bof

!include $(KODDIR)\kod.mak
