#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\elechunk.bof
BOFS = firechunk.bof coldchunk.bof shockchunk.bof acidchunk.bof holychunk.bof unholychunk.bof

!include $(KODDIR)\kod.mak
