#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\xeochctl.bof
BOFS  = xeofire.bof xeowater.bof xeoearth.bof xeoair.bof \
        xeoacid.bof xeounholy.bof xeoholy.bof xeoneru.bof \
        xeoill.bof xeobossfire.bof xeobossfire2.bof xeobossfire3.bof \
        xeobosswater.bof


!include $(KODDIR)\kod.mak
