#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\alchemy.bof
BOFS = mechanizedquiver.bof \
       elementalimbalance.bof \
       maintenance.bof \
       ringsustainment.bof

!include $(KODDIR)\kod.mak
