#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\passivequest.bof
BOFS = hp20pq1.bof \
       hp20pq2.bof \
       hp20pq3.bof \
       hp20pq4.bof \
       hp30pq1.bof \
       hp30pq2.bof \
       hp30pq3.bof \
       hp30pq4.bof \
       hp30pq5.bof \
       hp30pq6.bof \
       hp30pq7.bof \
       hp30pq8.bof \
       hp30pq9.bof \
       hp30pq10.bof \
       hp30pq11.bof \
       hp30pq12.bof \
       hp30pq13.bof \
       hp30pq14.bof \
       hp30pq15.bof
      

!include $(KODDIR)\kod.mak
