#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\passivequest.bof
BOFS = hp20pq1.bof \
       hp20pq2.bof \
       hp20pq3.bof \
       hp20pq4.bof \
       hp30pq1.bof \
       hp30pq1a.bof \
       hp30pq2.bof \
       hp30pq3.bof \
       hp30pq4.bof \
       hp30pq5.bof \
       hp30pq6.bof \
       hp30pq7.bof \
       hp30pq8.bof \
       hp30pq9.bof \
       hp30pq10.bof \
       hp30pq11.bof \
       hp30pq12.bof \
       hp30pq13.bof \
       hp30pq14.bof \
       hp30pq15.bof \
       hp40pq1.bof \
       hp40pq2.bof \
       hp40pq3.bof \
       hp40pq4.bof \
       hp35pq1.bof \
       hp35pq2.bof \
       hp35pq3.bof \
       hp50pq1.bof \
       hp50pq2.bof \
       hp50pq3.bof \
       hp60pq1.bof \
       hp80pq1.bof \
       hp90pq1.bof \
       hp90pq2.bof \
       hp90pq3.bof \
       hp90pq4.bof \
       hp90pq5.bof \
       hp100pq1.bof \
       hp100pq2.bof \
       hpMaxMinus20pq1.bof\
       hpMaxMinus20pq2.bof\
       hpMaxMinus10pq1.bof\
       hpMaxMinus10pq2.bof\
       hpMaxMinus10pq3.bof\
       hpMaxMinus10pq4.bof\
       hpMaxMinus10pq5.bof\
       hpMaxMinus10pq5a.bof\
       hpMaxMinus10pq5b.bof\
       hpMaxMinus10pq5c.bof\
       hpMaxMinus10pq5d.bof\
       hpMaxMinus10pq5e.bof\
       hpMaxMinus10pq6.bof\
       hpMaxMinus10pq7.bof\
       hpMaxMinus10pq8.bof\
       hpMaxMinus10pq9.bof\
       hpMaxMinus10pq10.bof\
       hpMaxMinus10pq11.bof\
       anyhpmazepq1.bof \
       anyhpreincpq1.bof\
       anyhpreincpq2.bof\
       anyhpreincpq3.bof \
       anyhplavafrogpq1.bof \
       anyhparmorypq1.bof \
       anyhpmazeexitpq1.bof \
       anyhpicedragonpq1.bof \
       shal6pq1.bof \
       shal6pq2.bof \
       anyhphighsorcerers.bof
      

!include $(KODDIR)\kod.mak
