#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\sorcery.bof
BOFS = bloodmagic.bof willsurge.bof forcespike.bof \
       volatilefocus.bof chargedclutch.bof somancy.bof damagemastery.bof \
       efficiency.bof empowerment.bof spiritlink.bof mysticgeometries.bof \
       inertform.bof

!include $(KODDIR)\kod.mak
