#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\tuttemple.bof

BOFS =  tuttemple1.bof tuttemple2.bof tuttemple2b.bof tuttemple3.bof \
    tuttemple4.bof tuttempleschool.bof

# Removed
#        a4.bof a5.bof b4.bof b5.bof b7.bof b8.bof c3.bof c8.bof c9.bof \
#        d8.bof d9.bof e8.bof e9.bof f5.bof f6.bof f7.bof f9.bof

!include $(KODDIR)\kod.mak
