#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\crystalmod.bof
BOFS = mobfiredamage.bof \
       mobcolddamage.bof \
       mobshockdamage.bof \
       mobhealth.bof \
       mobresists.bof

!include $(KODDIR)\kod.mak
