#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deserttwn.bof
BOFS  = nomadwiseman.bof xaerdunafterlife.bof desertbard.bof desertwitch.bof \
        desertbandit.bof deserttribesman.bof desertthief.bof nequzon.bof \
        iwodachprst.bof

!include $(KODDIR)\kod.mak
