#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\desert.bof

BOFS = desertpath1.bof desertdunes.bof desertcliffaccess.bof \
       desertcliffnoaccess1.bof desertcliffnoaccess2.bof \
       desertcliffnoaccess3.bof desertshore1.bof desertshore2.bof \
       desertshore3.bof desertriver1.bof desertriver2.bof desertbridge.bof \
       desertcaveraft.bof desertsandbar.bof desertsteppes.bof \
       desertdunes2.bof desertdunes3.bof deserttomb1.bof desertdunesroom.bof \
       desertbridge2.bof acidpath.bof desertriver3.bof \
       desertcity1.bof desertcity2.bof desertcanal.bof \
       frozencistern.bof palace.bof ziggurataltar.bof

!include $(KODDIR)\kod.mak
