#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\resist.bof
BOFS = resfire.bof resshock.bof rescold.bof resgood.bof resmagic.bof \
	resevil.bof resacid.bof acidstormbuff.bof shockstormbuff.bof

!include $(KODDIR)\kod.mak
