#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\highsorcerer.bof
BOFS  = highsorcererdeath.bof \
        highsorcererlife.bof \
        highsorcererlightning.bof \
        highsorcererfire.bof \
        highsorcerercold.bof \
        highsorcereracid.bof


!include $(KODDIR)\kod.mak
