#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\healspell.bof
BOFS = holyminor.bof \
       holymoderate.bof \
       holymajor.bof \
       firemajor.bof \
       holygroup.bof

!include $(KODDIR)\kod.mak
