#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\resring.bof
BOFS = acidring.bof coldring.bof firering.bof shokring.bof holyring.bof unholyring.bof

!include $(KODDIR)\kod.mak
