#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\armorrelic.bof
BOFS = defensearmorrelic.bof offensearmorrelic.bof meleearmorrelic.bof \
       puncharmorrelic.bof rangedarmorrelic.bof

!include $(KODDIR)\kod.mak
