#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\personalbounty.bof
BOFS = huntalegendarybounty.bof \
       huntamarauderbounty.bof \
       huntindomitables.bof

!include $(KODDIR)\kod.mak
