#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\leaguetwn.bof
BOFS  = advleaguejailer.bof advleagueseer.bof advleaguemonk.bof \
        advleaguemortician.bof \
        advleaguebountymaster.bof

!include $(KODDIR)\kod.mak
