#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\shard.bof
BOFS = basicshard.bof removeshard.bof majorshard.bof augmentshard.bof \
       empowermentshard.bof hstone.bof rerollshard.bof

!include $(KODDIR)\kod.mak
