#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\clanguage.bof
BOFS = orcishlanguage.bof \
       birdsonglanguage.bof \
       skitteraticlanguage.bof \
       sylvanlanguage.bof \
       amphibiclanguage.bof \
       necromanticlanguage.bof \
       biskalaniclanguage.bof \
       trollimaiclanguage.bof \
       primallanguage.bof \
       draconiclanguage.bof

!include $(KODDIR)\kod.mak
