#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\wrendmod.bof
BOFS = wfirerendmod.bof \
       wthrustrendmod.bof \
       wbludgeonrendmod.bof \
       wpiercerendmod.bof \
       wslashrendmod.bof \
       wcoldrendmod.bof \
       wshockrendmod.bof \
       wacidrendmod.bof \
       wholyrendmod.bof \
       wunholyrendmod.bof \
       willusionrendmod.bof \
       wweaponrendmod.bof \
       wmagicrendmod.bof

!include $(KODDIR)\kod.mak
