#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\underseachamber.bof

BOFS =  chamberdeath.bof \
        chamberjungle.bof \
        chamberchained.bof \
        chamberfractured.bof \
        chamberhexed.bof \
        chambermountain.bof \
        chamberscaled.bof \
        chambersea.bof \
        chamberserpent.bof \
        chambersky.bof \
        chambersword.bof \
        chamberhammer.bof
        

!include $(KODDIR)\kod.mak

