#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\objectatt.bof
BOFS = weaponobjectatt.bof \
       defmodobjectatt.bof \
       roomobjectatt.bof \
       battlerobjectatt.bof

!include $(KODDIR)\kod.mak