#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\shadowcraft.bof
BOFS = sanctification.bof \
       flowingcloth.bof \
       ironweave.bof

!include $(KODDIR)\kod.mak
