#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\shadowcraft.bof
BOFS = sanctification.bof \
       flowingcloth.bof \
       ironweave.bof \
       desecration.bof \
       woundmask.bof \
       pressurepoints.bof \
       touchofdeath.bof \
       unifiedblazon.bof \
       flickerstrike.bof \
       wayofthebird.bof

!include $(KODDIR)\kod.mak
