#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\hex.bof
BOFS = slow.bof \
       fester.bof \
       mute.bof \
       weaken.bof \
       exhaustion.bof \
       bestill.bof \
       becloud.bof \
       blackmantle.bof \
       drainhex.bof \
       antireshex.bof

!include $(KODDIR)\kod.mak
