#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\spell.bof
BOFS = animate.bof \
       apparitn.bof \
       atakspel.bof \
       bait.bof \
       boon.bof \
       brittle.bof \
       brthlife.bof \
       cdisease.bof \
       cpoison.bof \
       creafood.bof \
       creasphm.bof \
       creaweap.bof \
       crysmana.bof \
       cursewp.bof \
       debuff.bof \
       defile.bof \
       discord.bof \
       dispillu.bof \
       distill.bof \
       dmspell.bof \
       engrave.bof \
       fade.bof \
       fdeath.bof \
       finlrite.bof \
       flash.bof \
       forsight.bof \
       heal.bof \
       holysymb.bof \
       hospice.bof \
       illform.bof \
       itemench.bof \
       majheal.bof \
       manabomb.bof \
       morph.bof \
       multicst.bof \
       mysttch.bof \
       nodebrst.bof \
       persench.bof \
       portlife.bof \
       purge.bof \
       purify.bof \
       radiusench.bof \
       relay.bof \
       remcurse.bof \
       roomench.bof \
       seance.bof \
       shatter.bof \
       summrefl.bof \
       summtwin.bof \
       swap.bof \
       sweep.bof \
       teleportspell.bof \
       utility.bof \
       walspell.bof \
       movementspell.bof \
       wavespell.bof \
       creaholyshield.bof \
       convoke.bof \
       groupheal.bof \
       stonetoflesh.bof \
       giftofspirit.bof \
       giftofvitality.bof \
       markofdefense.bof \
       douse.bof \
       creahelmet.bof \
       creashield.bof \
       crearing.bof \
       creascroll.bof \
       detonate.bof \
       firebomb.bof \
       shockbomb.bof \
       spellbomb.bof

!include $(KODDIR)\kod.mak
