#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\storebox.bof
BOFS = woodbox.bof chest.bof smallbox.bof oldbox.bof nomadchest.bof \
       reliquary.bof

!include $(KODDIR)\kod.mak
