#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\storebox.bof
BOFS = woodbox.bof chest.bof smallbox.bof oldbox.bof nomadchest.bof \
       reliquary.bof shardfusingdevice.bof shardshatteringdevice.bof \
       mazechest.bof forge.bof leaguedonations.bof setleaguehometown.bof \
       scryingdevice.bof seapalacedevice.bof ladderforge.bof \
       laddershardfusingdevice.bof laddershardshatteringdevice.bof

!include $(KODDIR)\kod.mak
