#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\marauder.bof 
BOFS  = vallok.bof \
        geilong.bof \
        kal.bof \
        luganeon.bof \
        abu.bof \
        davinus.bof \
        zett.bof \
        lacie.bof \
        moxie.bof \
        moosico.bof \
        ronu.bof \
        toxus.bof \
        shindra.bof \
        jinora.bof \
        seaman.bof \
        bobo.bof \
        arabella.bof \
        cynn.bof \
        dannydiablo.bof \
        dyvora.bof \
        ellokent.bof \
        evila.bof \
        evilchrischan.bof \
        evilgar.bof \
        eviljj.bof \
        evilsunnycatt.bof \
        gon.bof \
        jamesbot.bof \
        kat.bof \
        mutantpros.bof \
        nog.bof \
        psy.bof \
        rocket.bof \
        rusco.bof \
        salem.bof \
        sammy.bof \
        seava.bof \
        sethbot.bof \
        shivron.bof \
        tamisc.bof \
        worm.bof 


!include $(KODDIR)\kod.mak
