#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\marauder.bof 
BOFS  = vallok.bof GeiLong.bof Kal.bof Luganeon.bof abu.bof Davinus.bof Zett.bof lacie.bof


!include $(KODDIR)\kod.mak
