#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\marauder.bof 
BOFS  = vallok.bof \
        geilong.bof \
        kal.bof \
        luganeon.bof \
        abu.bof \
        davinus.bof \
        zett.bof \
        lacie.bof \
        moxie.bof \
        moosico.bof \
        ronu.bof \
        toxus.bof \
        shindra.bof \
        jinora.bof \
        seaman.bof \
        bobo.bof


!include $(KODDIR)\kod.mak
