#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\shield.bof

BOFS = \
	metlshld.bof goldshld.bof knhtshld.bof \
	orcshld.bof guilshld.bof soldshld.bof \
	torch.bof steelshld.bof mithrilshld.bof \
   beermug.bof elfshld.bof

!include $(KODDIR)\kod.mak
