#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\movementspell.bof
BOFS = flamedash.bof \
       lightningstrike.bof \
       chargeattack.bof

!include $(KODDIR)\kod.mak
