#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\teleportspell.bof
BOFS = rescue.bof blink.bof elusion.bof deathrift.bof \
       guildhallrecall.bof recall.bof

!include $(KODDIR)\kod.mak
