#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\slayermod.bof
BOFS = insectslayer.bof \
       skeletonslayer.bof \
       zombieslayer.bof

!include $(KODDIR)\kod.mak
