#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\slayermod.bof
BOFS = insectslayer.bof \
       skeletonslayer.bof \
       zombieslayer.bof \
       unholyslayer.bof \
       kriipaslayer.bof \
       airslayer.bof \
       magicalslayer.bof \
       plantslayer.bof \
       elementalslayer.bof \
       humanoidslayer.bof

!include $(KODDIR)\kod.mak
