#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\desertafterlife.bof

BOFS = desertaldunes.bof desertaldunes2e.bof desertaldunes3e.bof \
       desertaldunes4e.bof desertaldunesvecka.bof \
       desertaldunes3w.bof \
       desertaldunes4w.bof

!include $(KODDIR)\kod.mak
