#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomthreat.bof
BOFS = coldthreat.bof heatthreat.bof acidthreat.bof lavathreat.bof \
       fallthreat.bof phasethreat.bof

!include $(KODDIR)\kod.mak