#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomthreat.bof
BOFS = coldthreat.bof heatthreat.bof acidthreat.bof lavathreat.bof \
       fallthreat.bof phasethreat.bof magmathreat.bof icewaterthreat.bof \
       acidprismthreat.bof humiditythreat.bof rainthreat.bof snowthreat.bof \
       chaosthreat.bof vigorthreat.bof junglenightthreat.bof \
       lifeprismthreat.bof deathprismthreat.bof \
       underwaterthreat.bof

!include $(KODDIR)\kod.mak
