#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bestiaryskill.bof
BOFS = clanguage.bof \
       minionlimitboost.bof \
       minionspeed.bof \
       preservespecimenskill.bof

!include $(KODDIR)\kod.mak
