#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\summonspell.bof
BOFS = summonabomination.bof \
       summonelemental.bof \
       summonelephant.bof \
       summonspiritwolf.bof

!include $(KODDIR)\kod.mak
