#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\helmet.bof
BOFS = helm.bof circlet.bof ivycircl.bof simphelm.bof mask.bof \
       knighthelm.bof runedhelm.bof spikedhelm.bof shades.bof

!include $(KODDIR)\kod.mak
