#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bestiary.bof
BOFS = binding.bof \
       speak.bof \
       markofaggression.bof \
       studycreaturespells.bof \
       releaseminion.bof \
       studycreatureresists.bof \
       markofmagic.bof \
       studycreaturecompliance.bof \
       permabinding.bof \
       permabindingevil.bof

!include $(KODDIR)\kod.mak
