#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bestiary.bof
BOFS = binding.bof \
       speak.bof \
       markofaggression.bof \
       studycreaturespells.bof

!include $(KODDIR)\kod.mak
