#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\crest.bof
BOFS = shalcrest.bof \
       qorcrest.bof \
       weaponcrest.bof \
       knightcrest.bof \
       banditrycrest.bof \
       farencrest.bof \
       witcherycrest.bof \
       sorcerycrest.bof \
       jalacrest.bof \
       riijacrest.bof \
       kraanancrest.bof \
       alchemycrest.bof \
       adventurercrest.bof \
       wizardcrest.bof \
       warriorcrest.bof \
       bestiarycrest.bof \
       shadowcraftcrest.bof \
       trickerycrest.bof

!include $(KODDIR)\kod.mak
