#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\wallelem.bof
BOFS =  wallfire.bof wallltng.bof poisfogc.bof web.bof asburstc.bof \
        vectorwall.bof


!include $(KODDIR)\kod.mak
