#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomstorm.bof
BOFS = gortstorm.bof acidstorm.bof shockstorm.bof heatstorm.bof coldstorm.bof

!include $(KODDIR)\kod.mak