#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\magicmod.bof
BOFS = resistancemod.bof protectionmod.bof woffensemod.bof wstatmod.bof \
       vitalmod.bof

!include $(KODDIR)\kod.mak
