#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\magicmod.bof
BOFS = resistancemod.bof protectionmod.bof woffensemod.bof wstatmod.bof \
       vitalmod.bof empmod.bof cstatmod.bof crystalmod.bof \
       leadershipmod.bof minionmod.bof slayermod.bof \
       indestructiblemod.bof

!include $(KODDIR)\kod.mak
