#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\fragment.bof
BOFS = firefragment.bof coldfragment.bof shockfragment.bof acidfragment.bof \
       unholyfragment.bof holyfragment.bof

!include $(KODDIR)\kod.mak
