#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\antireshex.bof
BOFS = vulnerability.bof \
       frailty.bof \
       humility.bof \
       corruption.bof \
       flammability.bof \
       conductivity.bof \
       algidity.bof \
       corrosion.bof

!include $(KODDIR)\kod.mak
