#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\numbitem.bof
BOFS = money.bof food.bof ammo.bof reagent.bof shard.bof \
       seacoins.bof

!include $(KODDIR)\kod.mak
