#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\resistancemod.bof
BOFS = fireresistmod.bof coldresistmod.bof shockresistmod.bof \
       acidresistmod.bof holyresistmod.bof unholyresistmod.bof \
       pierceresistmod.bof slashresistmod.bof bludgeonresistmod.bof \
       quakeresistmod.bof thrustresistmod.bof

!include $(KODDIR)\kod.mak
