#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\jasprtwn.bof
BOFS  = hzapoth.bof hzelder.bof hzsmith.bof hzbart.bof hzinnk.bof \
        tutwizard.bof tutwizard2.bof tutwizard2b.bof \
        qortutteacher.bof shaltutteacher.bof tutwizard3.bof \
        tutwizard4.bof farentutteacher.bof WCtutteacher.bof \
        riijatutteacher.bof jalatutteacher.bof kraantutteacher.bof \
        tutwizard5.bof

!include $(KODDIR)\kod.mak
