#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\boltspel.bof
BOFS = lightnin.bof fireball.bof smite.bof slitherb.bof \
       illwound.bof \
       shokfury.bof \
       splsacid.bof \
       vampdrn.bof \
       blasfire.bof \
       exfrost.bof \
       iciclevolley.bof \
       shieldbash.bof \
       brambleblast.bof \
       charmspel.bof

!include $(KODDIR)\kod.mak
