#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\mazeroom.bof

BOFS =  maze1.bof maze2.bof maze4a.bof mazesewer.bof mazebossroom.bof \
        maze4b.bof maze4c.bof maze5.bof mazenwc.bof mazenec.bof \
        mazesec.bof mazeswc.bof mazenwc.bof

!include $(KODDIR)\kod.mak
