#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\mazeroom.bof

BOFS =  maze1.bof maze2.bof maze4a.bof mazesewer.bof mazebossroom.bof \
        maze4b.bof maze4c.bof maze5.bof mazenwc.bof mazenec.bof \
        mazesec.bof mazeswc.bof mazenwc.bof mazesb.bof mazenb.bof \
        mazewb.bof mazeeb.bof mazeinterior3.bof mazetreasureroomspear.bof \
        mazeinteriorroom.bof mazelavafrogroom.bof mazearmorroom.bof \
        mazeexitroom.bof mazeentranceroom.bof \
        mazereincarnationroom.bof

!include $(KODDIR)\kod.mak
