#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\skill.bof
BOFS = profic.bof stroke.bof dodge.bof parry.bof assess.bof block.bof secwind.bof disarm.bof \
       banditry.bof stance.bof sorcery.bof witchery.bof knightcraft.bof alchemy.bof \
       bestiaryskill.bof breath.bof shadowcraft.bof

!include $(KODDIR)\kod.mak
