#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\skill.bof
BOFS = profic.bof stroke.bof dodge.bof parry.bof assess.bof block.bof secwind.bof disarm.bof banditry.bof stance.bof

!include $(KODDIR)\kod.mak
