#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\pforget.bof
BOFS = forgetsk.bof forgetfr.bof forgetsh.bof forgetkr.bof forgetqr.bof \
	forgetrj.bof forgetjl.bof forgetxwi.bof forgetvwi.bof forgetnwi.bof forgetiwi.bof \
   forgetsorc.bof forgetband.bof forgetkc.bof

!include $(KODDIR)\kod.mak
