#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\challenge.bof
BOFS = eachshardchallenge.bof \
       vitalschallenge.bof \
       reincarnatechallenge.bof \
       treasurechestschallenge.bof

!include $(KODDIR)\kod.mak
