#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\stance.bof
BOFS = lightfeet.bof swifthands.bof heavyarms.bof recklessheart.bof \
       focusedmind.bof poisedsoul.bof chargedclutchst.bof

!include $(KODDIR)\kod.mak
