#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\stance.bof
BOFS = lightfeet.bof swifthands.bof heavyarms.bof recklessheart.bof focusedmind.bof poisedsoul.bof chargedclutch.bof \
       chargedclutchst.bof castingstance.bof cleave.bof \
       heavyattacks.bof \
       lightattacks.bof \
       activeblocking.bof \
       activeparrying.bof \
       mysticstealth.bof \
       shadowstep.bof \
       loyalguard.bof \
       defiantstand.bof

!include $(KODDIR)\kod.mak
