#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\breath.bof
BOFS = mayurasana.bof \
       sirsasana.bof \
       salabhasana.bof \
       padmasana.bof \
       vrikshasana.bof \
       matsyasana.bof

!include $(KODDIR)\kod.mak
